file_format: "1"
id: ktbot
name: ktbot
type: shield
url: https://clicketysplit.ca/pages/leeloo
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
  - underglow
siblings:
  - ktbot_left
  - ktbot_right
