file_format: "1"
id: leeloo_rev2
name: ZMK-KTB
type: shield
url: https://clicketysplit.ca/pages/leeloo
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
  - underglow
siblings:
  - leeloo_rev2_left
  - leeloo_rev2_right
